Remove the http-client module import statement (#55)
This caused an error when trying to use npm-http-server
as it is not declared as a dependency in `package.json`

```
Error: Cannot find module 'http-client'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (.../node_modules/npm-http-server/PackageUtils.js:8:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```